apiVersion: apps/v1
kind: Deployment
metadata:
  name: finetuned-gemma-deployment
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemma-server
  template:
    metadata:
      labels:
        app: gemma-server
        ai.gke.io/model: gemma-2b
        ai.gke.io/inference-server: vllm
        examples.ai.gke.io/source: user-guide
    spec:
      serviceAccountName: finetuning-service-sa  # Ensure the service account has GCS access permissions
      containers:
      - name: inference-server
        image: us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20241101_0916_RC00
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "2"
            memory: "7Gi"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: "7Gi"
            ephemeral-storage: "10Gi"
            nvidia.com/gpu: 1
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install bitsandbytes>=0.44.0 && \
          mkdir -p /finetuned_model && \
          gsutil cp -r gs://finetuning-data-bucket/fine_tuned_model/* /finetuned_model/ && \  
          python3 -m vllm.entrypoints.api_server --model=/finetuned_model --tokenizer=/finetuned_model 
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HUGGING_FACE_TOKEN
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  selector:
    app: gemma-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
