apiVersion: batch/v1
kind: Job
metadata:
  name: finetune-job
  namespace: mlops
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: finetuner
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/memory-limit: "35Gi"
    spec:
      serviceAccountName: finetuning-service-sa   # created service account with necessary rights
      terminationGracePeriodSeconds: 600
      containers:
      - name: finetuner
        image: us-central1-docker.pkg.dev/mlops-airflow2/llm-finetuning/finetuning-service:latest   #IMAGE URL - update if required
        resources:
          limits:
            nvidia.com/gpu: "1"
        env:
        - name: TRAINING_DATASET_BUCKET
          value: "finetuning-data-bucket"
        - name: TRAINING_DATASET_PATH
          value: "prepared_data.jsonl"
        - name: MODEL_NAME
          value: "google/gemma-2-9b-it"
        - name: NEW_MODEL
          value: "gemma-finetuned"
        - name: MODEL_PATH
          value: "/model-data/model-gemma2/experiment"
        - name: EPOCHS
          value: "1"
        - name: TRAIN_BATCH_SIZE
          value: "1"
        - name: GRADIENT_ACCUMULATION_STEPS
          value: "1"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HUGGING_FACE_TOKEN
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /model-data
          readOnly: false
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: "finetuning-data-bucket"
            gcsfuseLoggingSeverity: warning
            implicitDirs: "true"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
      restartPolicy: OnFailure