# Build image and push to existing artifact registry
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - $_DEPLOY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME
      - .
      - '-f'
      - Dockerfile
    id: Build-image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME
    id: Push-image
images:
  - $_DEPLOY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME
substitutions:
  _PROJECT_ID: mlops-airflow2
  _SERVICE_NAME: finetuning-service
  _DEPLOY_REGION: us-central1
  _ARTIFACT_REGISTRY_REPO: llm-finetuning

